version: "2"

services:

  vuetify:
    build: "./vuetify"
    environment:
      - VUE_APP_API_SERVER
      - VUE_APP_THUNDERFOREST_APIKEY
      - VUE_APP_I18N_LOCALE
      - VUE_APP_I18N_FALLBACK_LOCALE
    volumes:
      - "./dist:/vuetify/dist"
      - "./vuetify/src:/vuetify/src"
      # - "static_files:/vuetify/dist"

volumes: {}
  # static_files: {}
  # db_files: {}
  # upload_files: {}
